//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotherBoard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MotherBoard()
        {
            this.PC = new HashSet<PC>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> TypeOfMemoryID { get; set; }
        public Nullable<int> ChipsetID { get; set; }
        public Nullable<int> SocketID { get; set; }
        public Nullable<int> PCI_E_ID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> EnergyConsumption { get; set; }
        public Nullable<int> FormFactorID { get; set; }
        public string PhotoLink { get; set; }
    
        public virtual Chipset Chipset { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual FormFactor FormFactor { get; set; }
        public virtual PCI_E PCI_E { get; set; }
        public virtual Socket Socket { get; set; }
        public virtual TypeOfMemory TypeOfMemory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC> PC { get; set; }
    }
}
