//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC()
        {
            this.PCCost = new HashSet<PCCost>();
            this.Service = new HashSet<Service>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> ProcessorID { get; set; }
        public Nullable<int> MotherBoardID { get; set; }
        public Nullable<int> TowerPCID { get; set; }
        public Nullable<int> VideocardID { get; set; }
        public Nullable<int> CoolingProcessorID { get; set; }
        public Nullable<int> RamID { get; set; }
        public Nullable<int> DataStorageID { get; set; }
        public Nullable<int> PowerSupplyID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CoolingProcessor CoolingProcessor { get; set; }
        public virtual DataStorage DataStorage { get; set; }
        public virtual MotherBoard MotherBoard { get; set; }
        public virtual PowerSupply PowerSupply { get; set; }
        public virtual Processor Processor { get; set; }
        public virtual Ram Ram { get; set; }
        public virtual TowerPC TowerPC { get; set; }
        public virtual Videocard Videocard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCCost> PCCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service { get; set; }
    }
}
