//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerSupply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PowerSupply()
        {
            this.PC = new HashSet<PC>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> PowerID { get; set; }
        public Nullable<int> ConectorCPUID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string PhotoLink { get; set; }
    
        public virtual ConectorCPU ConectorCPU { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC> PC { get; set; }
        public virtual Power Power { get; set; }
    }
}
