//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Processor()
        {
            this.PC = new HashSet<PC>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int SocketID { get; set; }
        public int TypeOfMemoryID { get; set; }
        public int CPUFamilyID { get; set; }
        public bool GraphicsCore { get; set; }
        public int ProcessorFrequencyID { get; set; }
        public Nullable<int> GenerationCPUID { get; set; }
        public int QuantityCoreID { get; set; }
        public int ManufacturerGPUID { get; set; }
        public decimal Cost { get; set; }
        public int EnergyConsumption { get; set; }
        public string PhotoLink { get; set; }
    
        public virtual CpuFamilyID CpuFamilyID1 { get; set; }
        public virtual GenerationCPU GenerationCPU { get; set; }
        public virtual ManufacturerGPU ManufacturerGPU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC> PC { get; set; }
        public virtual ProcessorFrequency ProcessorFrequency { get; set; }
        public virtual QuantityCore QuantityCore { get; set; }
        public virtual Socket Socket { get; set; }
        public virtual TypeOfMemory TypeOfMemory { get; set; }
    }
}
